language: node_js
node_js:
  - "5.6"
services:
  - mongodb
  - redis-server
  - elasticsearch
before_script:
  - sleep 15
  - npm install
script:
  - npm test
cache:
  directories:
    - node_modules
