language: node_js
node_js:
  - "5.6"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - mongodb-3.0-precise
    packages:
      - g++-4.8
      - mongodb-org-server
env:
  global:
    - CXX=g++-4.8
services:
  - mongodb
  - redis-server
  - elasticsearch
before_script:
  - sleep 15
  - npm install
script:
  - npm test
cache:
  directories:
    - node_modules
