language: node_js
node_js:
  - "5.0"
services:
  - mongodb
  - redis-server
before_script:
  - npm install -g gulp bower
  - cd dashboard-src
  - bower install
  - cd ..
script:
  - npm test
cache:
  directories:
    - node_modules
